# Generated by Django 3.0.5 on 2020-04-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0003_auto_20200407_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_joined',
        ),
    ]
