# Generated by Django 3.0.5 on 2020-04-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0005_auto_20200407_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
    ]
