# Generated by Django 3.0.5 on 2020-04-07 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0006_remove_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
