# Generated by Django 3.0.5 on 2020-04-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
    ]
